env:  
  node: true  
extends:  
  - plugin:@typescript-eslint/recommended  
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'  
parserOptions:
  project: ./tsconfig.json  
plugins:  
 - '@typescript-eslint'
rules:
 "@typescript-eslint/no-explicit-any": "off"