name: Build Docker Image and Release
on:
  push:
    branches: [ master ]

jobs:
 # Publishes a docker image of Kadocoin multi-wallet API and release files
  build-docker-image-and-release:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: Kado-Coin/Kadocoin-MultiWallet-API/Kadocoin-MultiWallet-API
          tag_with_ref: true
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master    
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with: 
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: "Latest"
           draft: false
           prerelease: false
           title: ${{ steps.package-version.outputs.current-version}}