name: Publish and Deploy Docker image to Caprover

on:
  push:
    branches: ['dev']

jobs:
  deploy_to_caprover:
    name: Push Docker image to DockerHub and GitHub Container Registry. Deploy image to Caprover.
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            dankore/kadocoin-multi-wallet-api
            ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Deploy to Caprover Using GitHub Actions
        uses: dankore/github-to-caprover@v.1.0.6
        with:
          server: "${{ secrets.CAPROVER_URL }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          appName: "${{ secrets.CAPROVER_APP_DEV }}"
          image: ghcr.io/kado-coin/kadocoin-multi-wallet-api:dev
      
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master    
      
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with: 
           repo_token: ${{ secrets.CR_PAT }}
           automatic_release_tag: latest
           draft: false
           prerelease: false
           title: ${{ steps.package-version.outputs.current-version}}